# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- develop

name: $(BuildID)-$(Build.SourceBranchName)
pool:
  vmImage: 'ubuntu-18.04'





steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.100'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'


- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'WebApp.WebApp.csproj'
    arguments: '-c Release -o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'publish artifact olympiad-build'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'olympiad-build'
    publishLocation: 'Container'