version: "3.8"

services:
    api:
        build: ${BACK_CONTEXT:-.}/deploy/api
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - ConnectionStrings__PostgresDataBase=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=olympiad-dev-db;Integrated Security=true;
           - RabbitMqQueueSettings__Host=rabbitmq
        restart: on-failure
        ports:
            - 5501:5501
        depends_on:
            - postgres
            - rabbitmq
    admin:
        build: ${BACK_CONTEXT:-.}/deploy/admin
        ports:
            - 5503:5503
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - ConnectionStrings__PostgresDataBase=User ID=postgres;Password=password;Server=postgres;Port=5432;Database=olympiad-dev-db;Integrated Security=true;
           - AdminServiceAdminSettings__OlympiadBaseAddress=http://api:5501
    executor:
        build: ${BACK_CONTEXT:-.}/deploy/executor
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - StartSettings__DockerEndPoint=http://dind:2375
        restart: on-failure
        depends_on:
            - api
            - dind
            - rabbitmq
    dind:
        image: docker:stable-dind
        privileged: true
        command: dockerd --host=tcp://0.0.0.0:2375 -l=debug
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    postgres:
        image: postgres:13-alpine
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        
    rabbitmq:
        ports:
            - 5672:5672
            - 8080:15672
        restart: on-failure
