version: '3'

services:
  clientapp:
    image: clientapp
    build:
      context: .
      dockerfile: ./ClientApp/Dockerfile
    ports:
      - 4200:80
  webapp:
    image: webapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 80:5000