version: '3'

services:
  clientapp:
    image: clientapp
    build:
      context: .
      dockerfile: ./ClientApp/Dockerfile
  webapp:
    image: webapp
    build:
      context: .
      dockerfile: ./WebApp/Dockerfile
    ports: 
      - 5000:5000