version: '3.4'

services:
  postgres:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=password
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 55471:80
    environment:
      - INIT_ROLES=true
    volumes:
      - ./WebApp/appsettings.Secret.json:/app/appsettings.Secret.json
    depends_on: 
      - postgres