version: "3.8"

services:
    api:
        build: ${BACK_CONTEXT:-.}/deploy/api
        ports:
            - 5501:5501
        depends_on:
            - postgres
            - rabbitmq
    executor:
        build: ${BACK_CONTEXT:-.}/deploy/executor
        depends_on:
            - rabbitmq
    postgres:
        image: postgres:13-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    rabbitmq:
        image: rabbitmq
        ports:
            - 5672:5672
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"

