version: "3.8"

services:
    api:
        image: rtuitlab/olympiad-api
        environment:
            - RabbitMqQueueSettings__Host=rabbitmq
    admin:
        image: rtuitlab/olympiad-admin
        environment:
            - RabbitMqQueueSettings__Host=rabbitmq
    executor:
        image: rtuitlab/olympiad-executor
        environment:
            - StartSettings__DockerEndPoint=unix:///var/run/docker.sock
            - RabbitMqQueueSettings__Host=rabbitmq
            - StartSettings__Address=http://api:5501
            - CONSOLE_MODE=Logs
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    rabbitmq:
        image: rabbitmq:3-management
