version: "3.8"

services:
    api:
        image: rtuitlab/olympiad-api
        environment:
            - ASPNETCORE_ENVIRONMENT=${SERVICE_ASPNETCORE_ENVIRONMENT}
            - ConnectionStrings__PostgresDataBase=${SERVICE_POSTGRES_DB}
            - RabbitMqQueueSettings__Host=${SERVICE_RABBITMQ_HOST}
        restart: on-failure
        depends_on:
            - postgres
            - rabbitmq
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    executor:
        image: rtuitlab/olympiad-executor
        environment:
            - ASPNETCORE_ENVIRONMENT=${SERVICE_ASPNETCORE_ENVIRONMENT}
            - RabbitMqQueueSettings__Host=${SERVICE_RABBITMQ_HOST}
            - StartSettings__Address=http://api:5501
            - StartSettings__DockerEndPoint=http://dind:2375
            - CONSOLE_MODE=Logs
        restart: on-failure
        depends_on:
            - rabbitmq
            - api
            - dind
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    dind:
        image: docker:stable-dind
        privileged: true
        command: dockerd --host=tcp://0.0.0.0:2375 -l=debug
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"  
