version: "3.8"

services:
    api:
        image: rtuitlab/olympiad-api
        environment:
            - ASPNETCORE_ENVIRONMENT=${SERVICE_ASPNETCORE_ENVIRONMENT}
            - ConnectionStrings__PostgresDataBase=${SERVICE_POSTGRES_DB}
            - RabbitMqQueueSettings__Host=${SERVICE_RABBITMQ_HOST}
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    postgres:
        image: postgres:13-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    rabbitmq:
        image: rabbitmq
        ports:
            - 5672:5672
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
