version: "3.8"

services:
    api:
        image: rtuitlab/olympiad-api
        env_file:
            - ${BACK_CONTEXT:-.}/api.env
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    executor:
        image: rtuitlab/olympiad-executor
        env_file:
            - ${BACK_CONTEXT:-.}/executor.env
        restart: on-failure
        depends_on:
            - api
            - dind
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    dind:
        image: docker:stable-dind
        privileged: true
        command: dockerd --host=tcp://0.0.0.0:2375 -l=debug
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    postgres:
        image: postgres:13-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    rabbitmq:
        image: rabbitmq
        ports:
            - 5672:5672
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
