version: '3.4'

services:
  postgres:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=password
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 5000:80
    environment:
      - INIT_ROLES=true
    depends_on: 
      - postgres
  docker:
    image: docker:stable-dind
    privileged: true
  executor:
    build:
      context: .
      dockerfile: ./Executor/Dockerfile
    depends_on: 
      - docker
      - webapp
