version: "3.8"

services:
    api:
        build: ${BACK_CONTEXT:-.}/deploy/api
        ports:
            - 5501:5501
        depends_on:
            - postgres
            - rabbitmq
    executor:
        build: ${BACK_CONTEXT:-.}/deploy/executor
        depends_on:
            - rabbitmq
    postgres:
        ports:
            - 5432:5432
    rabbitmq:
        ports:
            - 5672:5672
