version: "3.8"

services:
    api:
        image: rtuitlab/olympiad-api
        env_file:
            - ${BACK_CONTEXT:-.}/api.env
        deploy:
            resources:
                limits:
                    cpus: '0.30'
                    memory: 100M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    executor:
        image: rtuitlab/olympiad-executor
        env_file:
            - ${BACK_CONTEXT:-.}/executor.env
        environment:
            - StartSettings__DockerEndPoint=unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            resources:
                limits:
                    cpus: '0.30'
                    memory: 100M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    postgres:
        image: postgres:13-alpine
        environment:
            - POSTGRES_PASSWORD=password
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 300M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
    rabbitmq:
        image: rabbitmq
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 300M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
